name: master_ci

on:
  push:
    branches:
      - master


jobs:
  build:
    name: "java 16 build"
    runs-on: [self-hosted]
    steps:
      - name: check out
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: setup java 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          overwrite-settings: false
      - name: setup maven
        uses: stCarolas/setup-maven@v4.1
        with:
          maven-version: 3.8.1
#      - name: cache maven artifacts
#        uses: actions/cache@v2.1.6
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
#          restore-keys: ${{ runner.os }}-maven-
      - name: verify and check updates
        run: |
          mvn clean verify
          mvn versions:display-dependency-updates